--1)
    SELECT STUDENT_NO 학번,
           STUDENT_NAME 이름,
           TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
    FROM TB_STUDENT
    WHERE DEPARTMENT_NO = '002'
    ORDER BY 입학년도;
--2)
    SELECT 
        PROFESSOR_NAME,
        PROFESSOR_SSN
    FROM TB_PROFESSOR
    -- WHERE PROFESSOR_NAME NOT LIKE '___';
    WHERE LENGTH(PROFESSOR_NAME) != 3;
--3)
    SELECT PROFESSOR_NAME 교수이름 , 
        EXTRACT(YEAR FROM SYSDATE) - (19 ||SUBSTR(PROFESSOR_SSN,1,2)) 나이
    FROM TB_PROFESSOR
    WHERE SUBSTR(PROFESSOR_SSN, 8 , 1) = '1'
    ORDER BY 나이;
--4)
    SELECT SUBSTR(PROFESSOR_NAME , 2 ) 이름
    FROM TB_PROFESSOR;
--5)
    SELECT STUDENT_NO, STUDENT_NAME
    FROM TB_STUDENT
    WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT( YEAR FROM TO_DATE( SUBSTR(STUDENT_SSN , 1,6) )) > 19;
    
--6)  20201225
SELECT TO_CHAR(TO_DATE('20201225'),'DAY')
FROM DUAL;

--8) 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
-- WHERE ENTRANCE_DATE < '2000/01/01';
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9) 
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10)
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 11) 
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12)
SELECT SUBSTR(TERM_NO,1,4) 년도 , ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

-- 13)
SELECT DEPARTMENT_NO, COUNT( DECODE(ABSENCE_YN,'Y','1')  ) "휴학생수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 14)
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1;

-- 15)
SELECT NVL(SUBSTR(TERM_NO,1,4),'　') 년도, NVL(SUBSTR(TERM_NO,5,2),'　') 학기 , ROUND(AVG(POINT),1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO , 1,4) , SUBSTR(TERM_NO, 5, 2))
;














































