-- 10
CREATE OR REPLACE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT 
    STUDENT_NO,
    STUDENT_NAME,
    STUDENT_ADDRESS
   FROM TB_STUDENT;

--11
CREATE OR REPLACE VIEW VW_지도면담(학생이름, 학과이름, 지도교수이름) 
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, NVL(PROFESSOR_NAME,'지도교수업스')
FROM TB_STUDENT 
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO 
ORDER BY 2;

SELECT * FROM VW_지도면담;

--12
CREATE OR REPLACE VIEW VIEW_학과별학생수(DEPARTMENT_NAME, STUDENT_COUNT)
AS SELECT DEPARTMENT_NAME , COUNT(*)
   FROM TB_DEPARTMENT
   JOIN TB_STUDENT USING(DEPARTMENT_NO)
   GROUP BY DEPARTMENT_NAME;
   
-- 13
UPDATE VW_학생일반정보
SET 학생이름 = '민경민'
WHERE 학번 = 'A213046';

SELECT * FROM VW_학생일반정보
WHERE 학번 = 'A213046';

-- 14
CREATE OR REPLACE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT 
    STUDENT_NO,
    STUDENT_NAME,
    STUDENT_ADDRESS
   FROM TB_STUDENT
   WITH READ ONLY
;
-- 15
SELECT 과목번호, 과목이름, "누적수강생수(명)"
FROM (SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) "누적수강생수(명)"
      FROM TB_GRADE
      JOIN TB_CLASS USING(CLASS_NO)
      WHERE SUBSTR(TERM_NO,1,4) >= (SELECT MAX(SUBSTR(TERM_NO,1,4)) - 4 FROM TB_GRADE) 
      GROUP BY CLASS_NO, CLASS_NAME
      ORDER BY 3 DESC
)
WHERE ROWNUM <=3;








   
   